version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=app-local.yuan.yao
      - DB_URL=mongodb://mongodb/wtm
    ports:
      - 9999:9999
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest

  load-balancer:
    image: dockercloud/haproxy
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    restart: on-failure
